name: Frontend Run Type-check and Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  typecheck:
    name: Type-check Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint 
        run: npm run lint 

      - name: Type-check 
        run: npm run typecheck

